### ISSUE TITLE
remove reference to Solrizer

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/bulkrax#605] opened 2022-07-19 21:19 UTC
# issue
Solrizer will no longer be maintained. we will need to find another solution for [this line](https://github.com/samvera-labs/bulkrax/blob/bd683499bb52ae5df130f1fb266662ae55614767/app/parsers/bulkrax/csv_parser.rb#L225).

```
def set_ids_for_exporting_from_importer
      entry_ids = Importer.find(importerexporter.export_source).entries.pluck(:id)
      complete_statuses = Status.latest_by_statusable
                                .includes(:statusable)
                                .where('bulkrax_statuses.statusable_id IN (?) AND bulkrax_statuses.statusable_type = ? AND status_message = ?', entry_ids, 'Bulkrax::Entry', 'Complete')

      complete_entry_identifiers = complete_statuses.map { |s| s.statusable&.identifier&.gsub(':', '\:') }
      extra_filters = extra_filters.presence || '*:*'

      { :@work_ids => ::Hyrax.config.curation_concerns, :@collection_ids => [::Collection], :@file_set_ids => [::FileSet] }.each do |instance_var, models_to_search|
        instance_variable_set(instance_var, ActiveFedora::SolrService.post(
          extra_filters.to_s,
          fq: [
            %(#{::Solrizer.solr_name(work_identifier)}:("#{complete_entry_identifiers.join('" OR "')}")),
            "has_model_ssim:(#{models_to_search.join(' OR ')})"
          ],
          fl: 'id',
          rows: 2_000_000_000
        )['response']['docs'].map { |obj| obj['id'] })
      end
    end
```

**Comment by bkiahstroud** [comment] 2023-01-17 23:55
Duplicate of #699, which has been resolved

**Closed by bkiahstroud** 2023-01-17 23:55 UTC
