### ISSUE TITLE
export works, file sets and collections from one tenant and into another

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/bulkrax#591] opened 2022-07-13 18:19 UTC

**Comment by alishaevn** [comment] 2022-07-13 18:20
#570 may be a potential solution.

**Comment by kirkkwang** [comment] 2022-07-14 01:50
## Summary
When importing works with filesets to a tenant where the work does not already exist, the filesets do not succeed because the work does not exist at the time of creation.

## Issue

PALNI/PALCI is interested in migrating an entire tenant without developer support.  Currently the feature to export the entire tenant is  available through CSV export and the newly implemented BagIt export.  The issue arises when trying to import the works and filesets into a brand new tenant.  Since the works don't exist, the filesets do not get attached to them and instead new filesets are being created.  This means the filesets' metadata do not get transferred over to the new tenant.

A clunky workaround is separating the work csv entries and fileset csv entries, then initiate a csv import (just a csv file) and then a second import of the filesets along with the files (in a zip).

## Dev notes
`ImportFileSetJob` is supposed to reschedule if it cannot find the work to attach the fileset(s) to, however, currently it is not working as intended.

Problem found in `ImportFileSetJob#perform`
```ruby
parent_identifier = entry.raw_metadata[entry.related_parents_raw_mapping]&.strip
```
is setting `parent_identifier` to `nil` because `entry.related_parents_raw_mapping` is returning `"parents"` while the csv header is `"parents_1"`.

When hardcoding `"parents_1"`
```ruby
parent_identifier = entry.raw_metadata['parents_1']&.strip
```
the `ImportFileSetJob` does reschedule if the work isn't found.

**Comment by alishaevn** [comment] 2022-07-19 19:26
# todo
- export files only as a file set model, not as a header on the work so duplicates aren't created on import
- figure out why imported file set models sometimes return `parsed_metadata['file] = [nil]`

![image](https://user-images.githubusercontent.com/29032869/179342665-3052bc9f-562a-4d8c-8a56-5c067fe749b2.png)
![image](https://user-images.githubusercontent.com/29032869/179342680-f97b455d-dc24-4092-9fdc-0188aa40bcb3.png)
![image](https://user-images.githubusercontent.com/29032869/179342700-31ea4542-2e51-4e1f-8e24-1980e9ea7bbb.png)

**Closed** 2022-08-05 23:20 UTC
Labels: enhancement, minor-ver

**Comment by alishaevn** [comment] 2022-08-05 23:22
released in https://github.com/samvera-labs/bulkrax/releases/tag/v4.3.0.
