### ISSUE TITLE
Uninitialized constant error in CSV exporter based on importer

### ISSUE THREAD

**Issue by jwhitney** [samvera-labs/bulkrax#586] opened 2022-07-06 12:34 UTC
# Summary

We're getting an uninitialized constant error running a CSV exporter created from a successful importer, in Bulkrax v3.3.2 with Hyrax 3.4. 

# Expected behaviour

The exporter generates a CSV file for download based on records importer by the importer

# Actual behaviour

The exporter fails with error NameError - uninitialized constant Solrizer.  

<img width="1268" alt="Screen Shot 2022-07-06 at 08 31 52" src="https://user-images.githubusercontent.com/342343/177550774-b3542850-f462-4039-b8e1-b4cc4aa30701.png">

**Comment by alishaevn** [comment] 2022-08-05 22:39
might be related to #605

**Comment by bkiahstroud** [comment] 2023-01-17 23:56
Duplicate of #699, which has been resolved

**Closed by bkiahstroud** 2023-01-17 23:56 UTC
